SiteTree:
  content_review_gridfield_threshold: 500
  extensions:
    - SiteTreeContentReview
Group:
  extensions:
    - ContentReviewOwner
Member:
  extensions:
    - ContentReviewOwner
CMSPageEditController:
  extensions:
    - ContentReviewCMSExtension
CMSPageSettingsController:
  extensions:
    - ContentReviewCMSExtension
SiteConfig:
  extensions:
    - ContentReviewDefaultSettings